# 1.) Import the Credit Card Fraud Data From CCLE

Hayden Johnson

In [ ]:
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
drive.mount('/content/gdrive/', force_remount = True)

Mounted at /content/gdrive/


In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/MachineLearning/fraudTest.csv')

In [ ]:
df.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19   
1       302  Sales professional, IT  1990-01-17   
2     34496       Librarian, public  1970-10-21   
3     54767            Set designer  1987-07-25   
4      1126      Furniture designer  1955-07-06   

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

In [ ]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

# 2.) Select four columns to use as features (one just be trans_date_trans)

In [ ]:
df_select = df[['trans_date_trans_time','category','amt','city_pop','is_fraud']]

In [ ]:
df_select.head()

trans_date_trans_time        category    amt  city_pop  is_fraud
0   2020-06-21 12:14:25   personal_care   2.86    333497         0
1   2020-06-21 12:14:33   personal_care  29.84       302         0
2   2020-06-21 12:14:53  health_fitness  41.28     34496         0
3   2020-06-21 12:15:15        misc_pos  60.05     54767         0
4   2020-06-21 12:15:17          travel   3.19      1126         0

# 3.) Create a unique variable out of trans_date.

In [ ]:
type(df['trans_date_trans_time'][0])

str

In [ ]:
df['trans_date_trans_time']

0         2020-06-21 12:14:25
1         2020-06-21 12:14:33
2         2020-06-21 12:14:53
3         2020-06-21 12:15:15
4         2020-06-21 12:15:17
                 ...         
555714    2020-12-31 23:59:07
555715    2020-12-31 23:59:09
555716    2020-12-31 23:59:15
555717    2020-12-31 23:59:24
555718    2020-12-31 23:59:34
Name: trans_date_trans_time, Length: 555719, dtype: object

In [ ]:
df_select['lateNight'] = df_select.trans_date_trans_time.str[11:]

<ipython-input-17-d96a938ae22a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select['lateNight'] = df_select.trans_date_trans_time.str[11:]


In [ ]:
df_select['lateNight'] = df_select["lateNight"].str.replace(":","")

<ipython-input-18-7193b2fb3efc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select['lateNight'] = df_select["lateNight"].str.replace(":","")


In [ ]:
df_select['lateNight'] = df_select['lateNight'].astype(int)

<ipython-input-19-4e6d94f9f75a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select['lateNight'] = df_select['lateNight'].astype(int)


In [ ]:
lateNightFraud = list()
for i in df_select['lateNight']:
  if i >= 230000 and i <= 233000:
    lateNightFraud.append(1)
  else:
    lateNightFraud.append(0)

In [ ]:
df_select['lateNightFraud'] = lateNightFraud

<ipython-input-21-4bf4e4543159>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select['lateNightFraud'] = lateNightFraud


In [ ]:
df_select

trans_date_trans_time        category     amt  city_pop  is_fraud  \
0        2020-06-21 12:14:25   personal_care    2.86    333497         0   
1        2020-06-21 12:14:33   personal_care   29.84       302         0   
2        2020-06-21 12:14:53  health_fitness   41.28     34496         0   
3        2020-06-21 12:15:15        misc_pos   60.05     54767         0   
4        2020-06-21 12:15:17          travel    3.19      1126         0   
...                      ...             ...     ...       ...       ...   
555714   2020-12-31 23:59:07  health_fitness   43.77       519         0   
555715   2020-12-31 23:59:09       kids_pets  111.84     28739         0   
555716   2020-12-31 23:59:15       kids_pets   86.88      3684         0   
555717   2020-12-31 23:59:24          travel    7.99       129         0   
555718   2020-12-31 23:59:34   entertainment   38.13    116001         0   

        lateNight  lateNightFraud  
0          121425               0  
1          121433               0  
2          121453               0  
3          121515               0  
4          121517               0  
...           ...             ...  
555714     235907               0  
555715     235909               0  
555716     235915               0  
555717     235924               0  
555718     235934               0  

[555719 rows x 7 columns]

In [ ]:
#df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

In [ ]:
#df_select['time_var']=[i.second for i in df['trans_date_trans_time']]

In [ ]:
dummies = pd.get_dummies(df_select['category'])
X = pd.concat([dummies, df_select[['amt','city_pop','lateNightFraud']]], axis = 1)
y = df_select['is_fraud']

In [ ]:
df_select.describe()

amt      city_pop       is_fraud      lateNight  \
count  555719.000000  5.557190e+05  555719.000000  555719.000000   
mean       69.392810  8.822189e+04       0.003860  131070.313122   
std       156.745941  3.003909e+05       0.062008   68130.058615   
min         1.000000  2.300000e+01       0.000000       0.000000   
25%         9.630000  7.410000e+02       0.000000   73925.000000   
50%        47.290000  2.408000e+03       0.000000  140906.000000   
75%        83.010000  1.968500e+04       0.000000  190509.500000   
max     22768.110000  2.906700e+06       1.000000  235959.000000   

       lateNightFraud  
count   555719.000000  
mean         0.025799  
std          0.158535  
min          0.000000  
25%          0.000000  
50%          0.000000  
75%          0.000000  
max          1.000000

In [ ]:
#X.head()

# 4.) Oversample the data (this will be your training data).

Skip Me!

# 5.) Train a Logistic regression.

In [ ]:
df_select.dtypes

trans_date_trans_time     object
category                  object
amt                      float64
city_pop                   int64
is_fraud                   int64
lateNight                  int64
lateNightFraud             int64
dtype: object

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [ ]:
log_reg = LogisticRegression().fit(X,y)

In [ ]:
X_train, X_test, y_train,  y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)
reg = LogisticRegression()
reg.fit(X_train, y_train)
reg.predict_proba(X_test)

array([[0.99778683, 0.00221317],
       [0.99654275, 0.00345725],
       [0.99692959, 0.00307041],
       ...,
       [0.99480586, 0.00519414],
       [0.99745492, 0.00254508],
       [0.99639407, 0.00360593]])

# 6.) The company you are working for wants to target at a False Positive rate of 5% what threshold should you use? (Use oversampled data)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
#confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt


probs = reg.predict_proba(X_test)

fpr, tpr, thresholds = roc_curve(y_test, probs[:, 1])

threshold_index = np.abs(fpr - 0.05).argmin()
threshold = thresholds[threshold_index]

threshold

0.005532841343351329

In [ ]:
y_preds = (probs[:,1] > threshold).astype(int)

conf_matrix = confusion_matrix(y_test, y_preds)

print(conf_matrix)

[[104735   5983]
 [   104    322]]


# 7.) If the company makes .02*amt on True transactions and loses -amt on False (Use original data)

In [ ]:
df_temp = df_select.copy()

In [ ]:
df_temp['pred'] = log_reg.predict(X)

In [ ]:
df_temp = df_temp[['pred', 'is_fraud', 'amt']]

In [ ]:
df_temp['factor'] = np.where(df_temp['pred'] == df_temp['is_fraud'], .02, -1)

In [ ]:
df_temp['profit'] = df_temp['is_fraud']*df_temp['factor']

In [ ]:
Profit = sum(df_temp['profit'])
Profit

-2145.0

# 8.) Using Logistic Regression Lasso to inform you. Would you use the selected features in a trusted prediction model?

In [ ]:
# Create an instance of the logistic regression class
clf = LogisticRegression(penalty='l1', solver = 'saga')

# Fit the model to the data
clf.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(penalty='l1', solver='saga')

In [ ]:
probs = clf.predict_proba(X_test)

fpr, tpr, thresholds = roc_curve(y_test, probs[:, 1])

threshold_index = np.abs(fpr - 0.05).argmin()
threshold = thresholds[threshold_index]

threshold

0.4823733392530006

In [ ]:
y_preds = (probs[:,1] > threshold).astype(int)

conf_matrix = confusion_matrix(y_test, y_preds)

print(conf_matrix)

[[105180   5538]
 [   423      3]]


In [ ]:
clf.predict_proba(X_test)

array([[9.18185159e-01, 8.18148411e-02],
       [9.60780727e-01, 3.92192730e-02],
       [5.67636780e-01, 4.32363220e-01],
       ...,
       [9.99999999e-01, 7.22880372e-10],
       [5.63606267e-01, 4.36393733e-01],
       [6.50061849e-01, 3.49938151e-01]])

There are way to many true positives and hardly any true negatives. The probabilities for the variables are essentially zero, so I would not use this in a trusted prediction model.